
[colors]

# Primary colors
[colors.primary]
background = "0xf9f5d7"
foreground = "0x514036"

# Cursor colors
[colors.cursor]
text = "0xf9f5d7"
cursor = "0x7c6f64"

# Selection colors
[colors.selection]
text = "0xf9f5d7"
background = "0x514036"

# Normal colors (color0–color7)
[colors.normal]
black   = "0xd5c4a1" # color0
red     = "0xbd4848" # color1
green   = "0x69752d" # color2
yellow  = "0xb15509" # color3
blue    = "0x45707a" # color4
magenta = "0x945e80" # color5
cyan    = "0x4b795c" # color6
white   = "0x514036" # color7

# Bright colors (color8–color15)
[colors.bright]
black   = "0x928374" # color8
red     = "0xbd4848" # color9
green   = "0x69752d" # color10
yellow  = "0x9d6207" # color11
blue    = "0x45707a" # color12
magenta = "0x945e80" # color13
cyan    = "0x4b795c" # color14
white   = "0x514036" # color15
